#!/usr/bin/env bash
# Manages a PID file and handles signals while looping infinitely
echo "$$" > /var/run/myscript.pid

trap 'echo "I hate the kill command"' SIGINT
trap 'echo "Y u no love me?!"; rm -f /var/run/myscript.pid; exit' SIGQUIT
trap 'rm -f /var/run/myscript.pid; exit' SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
